// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./components/organisms/Comment.vue')['default']
    Ranking: typeof import('./components/organisms/Ranking.vue')['default']
    README: typeof import('./components/README.md')['default']
    Star: typeof import('./components/atoms/Star.vue')['default']
  }
}

export { }
